//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThemeBot
{
    using System;
    using System.Data.Entity;
    using Microsoft.Win32;
    using System.Data.Entity.Infrastructure;
    
    public partial class tdthemeEntities : DbContext
    {
        public tdthemeEntities()
            : base(RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry64).OpenSubKey("SOFTWARE\\ThemeBot").GetValue("BotConnectionString").ToString())
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Theme> Themes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Download> Downloads { get; set; }
    }
}
